apiVersion: batch/v1
kind: CronJob
metadata:
  name: mosquitto-restarter
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: mosquitto-restarter
          restartPolicy: OnFailure
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
                - kubectl
                - rollout
                - restart
                - deployment/mosquitto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mosquitto-restarter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mosquitto-restarter
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["mosquitto"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mosquitto-restarter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mosquitto-restarter
subjects:
  - kind: ServiceAccount
    name: mosquitto-restarter
